language: python

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install aiohttp
  - pip install aiohttp_cors
  - pip install click
  - pip install peewee
  - pip install asyncpg
  - pip install msgpack
  - pip install wtforms
  - pip install requests
  - pip install psycopg2-binary
  - pip install pytest-asyncio
  - pip install pytest-cov
  - pip install codecov

before_script:
  - python setup.py install

script:
  - py.test --cov=slim tests

after_script:
  - codecov --token=1227a871-bf41-433b-8ef1-50a850a00f9d
